version: '2'

services:
  consul:
    container_name: consul
    image: consul
    ports:
      - "8300"
      - "8400"
      - "8500"
    restart: always
  registrator:
    container_name: registrator
    image: gliderlabs/registrator:master
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: consul://consul:8500
    restart: always
    depends_on:
      - consul
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379
    restart: always
    depends_on:
      - registrator
  test:
    container_name: consul-test
    build: ./test
    image: anthcourtney/consul-test
    depends_on:
      - redis

networks:
  default:
